server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: howdb
    password: korea1234
    url: jdbc:mysql://localhost:3306/howdb
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none #create, update, none
    show-sql: true
    open-in-view: true
